# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse2004(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: str=None, label: str=None, date: str=None):
        """
        InlineResponse2004 - a model defined in Swagger

        :param id: The id of this InlineResponse2004.
        :type id: str
        :param label: The label of this InlineResponse2004.
        :type label: str
        :param date: The date of this InlineResponse2004.
        :type date: str
        """
        self.swagger_types = {
            'id': str,
            'label': str,
            'date': str
        }

        self.attribute_map = {
            'id': 'id',
            'label': 'label',
            'date': 'date'
        }

        self._id = id
        self._label = label
        self._date = date

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.
        :rtype: InlineResponse2004
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """
        Gets the id of this InlineResponse2004.
        CURIE-encoded identifier to an associated external resources (e.g. PMID of a pubmed citation) 

        :return: The id of this InlineResponse2004.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """
        Sets the id of this InlineResponse2004.
        CURIE-encoded identifier to an associated external resources (e.g. PMID of a pubmed citation) 

        :param id: The id of this InlineResponse2004.
        :type id: str
        """

        self._id = id

    @property
    def label(self) -> str:
        """
        Gets the label of this InlineResponse2004.
        canonical human readable and searchable label of the annotation (i.e. comment, matched sentence, etc.) 

        :return: The label of this InlineResponse2004.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """
        Sets the label of this InlineResponse2004.
        canonical human readable and searchable label of the annotation (i.e. comment, matched sentence, etc.) 

        :param label: The label of this InlineResponse2004.
        :type label: str
        """

        self._label = label

    @property
    def date(self) -> str:
        """
        Gets the date of this InlineResponse2004.
        publication date of annotation (generally of format 'yyyy-mm-dd') 

        :return: The date of this InlineResponse2004.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date: str):
        """
        Sets the date of this InlineResponse2004.
        publication date of annotation (generally of format 'yyyy-mm-dd') 

        :param date: The date of this InlineResponse2004.
        :type date: str
        """

        self._date = date

